# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-20 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mobile',
            field=models.BigIntegerField(default=1, help_text='用于手机验证码登录', unique=True, verbose_name='手机'),
            preserve_default=False,
        ),
    ]
